platform:ios, '8.0'

use_frameworks!

target 'YYProjectNew' do

pod 'Masonry', '~> 1.0.2'
pod 'Aspects', '~> 1.4.1'
pod 'ReactiveObjC', '~> 2.1.2'
pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'GTMBase64', '~> 1.0.0'

end
